<?php
/**
 * Created by PhpStorm.
 * User: YC
 * Date: 2017/4/29
 * Time: 13:59
 */

namespace app\common\controller;

use app\common\util\ConfigApi;
use think\Config;
use think\Controller;
use think\exception\HttpResponseException;
use think\Response;
use think\Url;
use think\View as ViewTemplate;

class BaseCotroller extends Controller
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        //注册配置项
        ConfigApi::config();
    }


    
}